--Crear tablas
CREATE TABLE producto (id INTEGER NOT NULL, nombre VARCHAR (45), descripcion VARCHAR (45), estado VARCHAR (3),  PRIMARY KEY (ID)); 
CREATE TABLE kardex (id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) NOT NULL, fecha TIMESTAMP, id_catologo INTEGER NOT NULL, detalle VARCHAR (45), ent_catidad INTEGER, ent_valor_unitario DECIMAL(10,2), ent_valor_total DECIMAL(10,2), sal_catidad INTEGER, sal_valor_unitario DECIMAL(10,2), sal_valor_total DECIMAL(10,2), exi_catidad INTEGER, exi_valor_unitario DECIMAL(10,2), exi_valor_total DECIMAL(10,2), stock_minimo INTEGER, PRIMARY KEY (ID));
CREATE TABLE persona (id INTEGER NOT NULL, identificacion VARCHAR(15), nombre VARCHAR(45), ciudad VARCHAR(45), correo_electronico VARCHAR(45), direccion VARCHAR(45), telefono VARCHAR(45), tipo_persona VARCHAR(3), username VARCHAR(45), password VARCHAR(256), estado VARCHAR(3),  PRIMARY KEY (ID));
--insert tabla Producto
insert into producto (id, nombre, descripcion, estado) values (1, 'Camisetas talla S', 'Camiseta de superheroe','ACT');
insert into producto (id, nombre, descripcion, estado) values (2, 'Camisetas talla M', 'Camiseta de superheroe','ACT');
insert into producto (id, nombre, descripcion, estado) values (3, 'Vaso Spiderman 20 onz', 'Vaso de superheroe','ACT');
insert into producto (id, nombre, descripcion, estado) values (4, 'Comic Hulk', 'Comic de superheroes','ACT');
insert into producto (id, nombre, descripcion, estado) values (5, 'Comic Linterna Verde', 'Comic de superheroes','ACT');
insert into producto (id, nombre, descripcion, estado) values (6, 'Juguete Iron man', 'Juguete de superheroe','ACT');
insert into producto (id, nombre, descripcion, estado) values (7, 'Accesorios', 'Accesorios Superheroe','ACT');
--insert tabla producto
insert into kardex (id, fecha, id_catologo, detalle, ent_catidad, ent_valor_unitario, ent_valor_total, sal_catidad, sal_valor_unitario, sal_valor_total, exi_catidad, exi_valor_unitario, exi_valor_total, stock_minimo) values (1, '2022-01-19 17:38:00', 1, 'Compra incial Camiseta S', 50, 10, 500, null, null, null, 50,10, 500, 3);
insert into kardex (id, fecha, id_catologo, detalle, ent_catidad, ent_valor_unitario, ent_valor_total, sal_catidad, sal_valor_unitario, sal_valor_total, exi_catidad, exi_valor_unitario, exi_valor_total, stock_minimo) values (2, '2022-01-19 17:38:00', 2, 'Compra incial Camiseta M', 30, 10.5, 315, null, null, null, 30,10.50, 315, 3);
insert into kardex (id, fecha, id_catologo, detalle, ent_catidad, ent_valor_unitario, ent_valor_total, sal_catidad, sal_valor_unitario, sal_valor_total, exi_catidad, exi_valor_unitario, exi_valor_total, stock_minimo) values (3, '2022-01-19 17:38:00', 3, 'Compra incial Vaso', 50, 10, 500, null, null, null, 20, 5, 100, 2);
insert into kardex (id, fecha, id_catologo, detalle, ent_catidad, ent_valor_unitario, ent_valor_total, sal_catidad, sal_valor_unitario, sal_valor_total, exi_catidad, exi_valor_unitario, exi_valor_total, stock_minimo) values (4, '2022-01-19 17:38:00', 4, 'Compra incial Comic', 50, 10, 500, null, null, null, 25, 1.50, 37.50, 3);
insert into kardex (id, fecha, id_catologo, detalle, ent_catidad, ent_valor_unitario, ent_valor_total, sal_catidad, sal_valor_unitario, sal_valor_total, exi_catidad, exi_valor_unitario, exi_valor_total, stock_minimo) values (5, '2022-01-19 17:38:00', 5, 'Compra incial Comic', 50, 10, 500, null, null, null, 25,1.50, 37.50, 3);
insert into kardex (id, fecha, id_catologo, detalle, ent_catidad, ent_valor_unitario, ent_valor_total, sal_catidad, sal_valor_unitario, sal_valor_total, exi_catidad, exi_valor_unitario, exi_valor_total, stock_minimo) values (6, '2022-01-19 17:38:00', 6, 'Compra incial Juguete', 50, 10, 500, null, null, null, 10,8, 80, 3);
insert into kardex (id, fecha, id_catologo, detalle, ent_catidad, ent_valor_unitario, ent_valor_total, sal_catidad, sal_valor_unitario, sal_valor_total, exi_catidad, exi_valor_unitario, exi_valor_total, stock_minimo) values (7, '2022-01-19 17:38:00', 7, 'Compra incial Accesorio', 50, 10, 500, null, null, null, 50,10, 500, 3);
insert into kardex (id, fecha, id_catologo, detalle, ent_catidad, ent_valor_unitario, ent_valor_total, sal_catidad, sal_valor_unitario, sal_valor_total, exi_catidad, exi_valor_unitario, exi_valor_total, stock_minimo) values (8, '2022-01-19 17:38:00', 7, 'Compra incial Accesorio', 10, 10, 200, null, null, null, 60,10, 600, 3);
--insert tabla persona
insert into persona (id, identificacion, nombre, ciudad, correo_electronico, direccion, tipo_persona, username, password, estado) values (1,'123456789','Jose','Quito','jose@hotmail.com','Turubamba','CLI','jose','1ec4ed037766aa181d8840ad04b9fc6e195fd37dedc04c98a5767a67d3758ece','ACT');   
insert into persona (id, identificacion, nombre, ciudad, correo_electronico, direccion, tipo_persona, username, password, estado) values (2,'9999000088','Mayra','Quito','mayra@hotmail.com','La Internacional','ADM','mayra','99032fb72a5e1725a3df5ea44e6dce405c5f5b1b2ef34b24dd2e6fab8c54d998','ACT');


